 name                
 apellido            
 email               
 email_verified_at   
 password            
 pass_crypt          
 referido            
 myrefcode           
 admin               
 telefono            
 empresa             
 remember_token      
 active              
 created_at          
 updated_at          
 usuario_legacy      
 medio_de_contacto 